자바 강의 15일차 / 첫 시험일
===================
2022.06.16
-------------------

> 아 오늘은 시험일이었다. 어제 주신 문제들 덕분에 내 실력을 알게 되었고,
>   
>내 현재 상태를 알 수 있었다. 사실 어제 문제가 없었다면 난 한문장도 못풀고 나오게 됐을 것 같다.   
>    
>어제를 기준으로 점점 코드가 눈에 익는 것 같다.   
>   
>사람들이 은근히 IDE의 강점을 안쓰고 있다는 것을 알게되어버렸다.   
>   
>글을 보고 있다면 이클립스에서 오류가 나는 부분의 빨간색에 커서를 올리는 습관을 들이는것을 권장한다.   
>   
>오류를 고칠 수 있는 파란 메세지가 나온다면 여러 파란 글씨 중 어떻게 고쳐야 맞게 동작할 지 생각하는 습관을 들이고,   
>   
>오류를 고쳐주는 파란글씨가 나오지 않는다면 지금 당신은 무언가 잘못 쓰고 있다는 것을 컴퓨터가 알려주는 것이니 맞는 방법을 찾을 때 까지 고민하고 또 고민해라.
>   
>이걸 모르고 있는 것과 알고 있는 것은 천지 차이라고 생각이 든다.   
>   
>깨달음을 얻은 기분이다... 오늘은 시험을 보고 오후 3시까지 개인공부시간이었기에 많은 것을 배우진 않았다.
>   
>오류가 나는 exception의 해결(try- catch- finally)를 배웠고 개인 검색을 통해 (try with resource)를 알게 되었다.   

```java
package koreait.day15;

import java.util.Scanner;

public class C62_ExceptionTest {

	public static void main(String[] args) {
		/*
		 * 문법오류: int a= 4.1; 과 같이 컴파일 자체가 안되는 것. Exception 요약 : 문법오류가 아닙니다. 실행하면서 발생하는
		 * 오류 입니다.(발생가능성을 고려해서 프로그래밍해야합니다.) -> 원인에 따라 다른이름 XXXXException 이 발생하고 이들은
		 * Exception 클래스의 자식 클래스입니다. -> Exception 이 실행 중에 발생하면 그 이후는?..... 프로그램이 그 시점부터
		 * 중단됩니다. 따라서, Exception 을 예상하고 프로그램이 중단되지 않도록 프로그램 구현을 해야합니다.
		 */

		// Exception 예시3 : java.util.InputMismatchException(정수 외의 다른 문자를 입력하면 생김)
		Scanner sc = new Scanner(System.in);
		System.out.println("정수입력>>>");
		// int a = sc.nextInt(); // 키보드입력을 정수로 변환해서 변수에 저장합니다.
		int n = Integer.parseInt(sc.nextLine());
		// 숫자 외에 다른 문자를 입력하면 java.lang.NumberFormatException발생.
		System.out.println("당신이 입력한 값" + n);

		// Exception 예시2: java.lang.ArrayIndexOutOfBoundsException (배열의 경계를 넘어간 오류)
		int[] nums = new int[5]; // 배열선언 : 요소 5개입니다.
		nums[5] = 100; // 인덱스가 4번까지밖에 없음.

		// Exception 예시1 : java.lang.NullPointerException(객체 참조가 null이면 메소드 실행 불가 라는 뜻)
		String message = null;

		char temp = message.charAt(0); // message 문자열에서 첫번째(0) 글자 1개 가져옵니다.

	}

}
```
```java
package koreait.day15;

import java.util.InputMismatchException;
import java.util.Scanner;

public class C63_TryCatchTest {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		// try형식
		try {
			// Exception 가능성이 있는 명령을 작성 -> 오류가 생기면 catch로감.
			// 이 위치에서 변수선언하면 try의 지역변수

		} catch (NullPointerException e) {
			// 오류 원인에 따른 Exception 종류 검사.
			// 지금은 NullPointException일때만 아래 명령 시행
			e.printStackTrace(); // 오류 추적을 위해 원인을 출력(기존 Exception 출력내용)
		}

		catch (InputMismatchException e) {
			// catch는 여러번 작성 가능

		} finally {
			// 마지막으로, 최종적으로 : 오류 발생 상관없이 실행되는 부분

		}

		sc.close();

	}

}
```
```java
package koreait.day15;

import java.util.Scanner;

public class C64_TryCatchEx1 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		try {
			String message = null;
			int cnt = message.length();

			System.out.println("정수입력>>>");
			// int n = sc.nextInt();
			int n = Integer.parseInt(sc.nextLine());
			// 이건 java.lang.NumberFormatException이 뜸.
			System.out.println("당신이 입력한 값 :" + n);
			// }catch(Exception e{ 오류 원인에 따른 Exception종류 검사.
			// }catch(NullPointerException e){
			// |기호는 bit 단위 or 연산 : Exception이 비트값으로 설정

		} catch (NullPointerException | NumberFormatException e) {
			// 발생한 오류정보를 Exception 객체로 관리하고 이에 대한 참조변수는 e임
			System.out.println("오류 발생" + e.getMessage());
			System.out.println("사용자 기능에 문제가 발생했습니다.");
		} finally {
			sc.close();
		}
		System.out.println("프로그램 끝!");
	}

}
```
```java
package koreait.day15;

import java.io.File; //io= input, output 입출력과 관련된 기능의 클래스
import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class C65_FileWriteTest {

	public static void main(String[] args) {

		String filename = "D:\\study\\자바테스트.txt";

		File file = new File(filename);

		// Scanner : 입력기능을 갖는 클래스
		// PrintWriter : 출력 기능을 갖고 있는 클래스
		// Unhandled exception type FileNotFoundException : 오류의 가능성이 있으므로 try catch가
		// 필요하다는 뜻.
		PrintWriter pw = null;
		try {
			pw = new PrintWriter(file);
			pw.println("모모 90 89 82");
			pw.println("다현 89 90 82");
			pw.println("나연 82 89 90");
			System.out.println("파일 출력이 완료되었습니다");// System.out : 표준 출력

		} catch (FileNotFoundException e) {
			System.out.println("사용자 오류발생 : " + e.getMessage());
			e.printStackTrace();
		} finally {
			pw.close();
		}

	}

}
```
```java
package koreait.day15;

import java.io.File; //io= input, output 입출력과 관련된 기능의 클래스
import java.io.FileNotFoundException;
import java.util.Scanner;

public class C66_FilerReadTest2 {

	public static void main(String[] args) {

		String filename = "D:\\study\\자바테스트2.txt";

		File file = new File(filename);

		// Scanner : 입력기능을 갖는 클래스
		// PrintWriter : 출력 기능을 갖고 있는 클래스
		// Unhandled exception type FileNotFoundException : 오류의 가능성이 있으므로 try catch가
		// 필요하다는 뜻.
		Scanner sc = null;
		try {
			sc = new Scanner(file); // System.in을 쓰면 표준입력(콘솔입력)
//			
//			System.out.println("파일에서 읽은 내용 :" + sc.nextLine());
//			System.out.println("파일에서 읽은 내용 :" + sc.nextLine());
//			System.out.println("파일에서 읽은 내용 :" + sc.nextLine());
//			
			while (sc.hasNext()) { // 구분자 엔터를 기준으로 다음 데이터가 있으면 true
				System.out.println(sc.nextLine());
			}

			System.out.println("파일 읽기가 완료되었습니다");// System.out : 표준 출력

		} catch (FileNotFoundException e) {
			// 입력기능에는 파일이 없으면 Exception이 발생
			System.out.println("사용자 오류발생 : " + e.getMessage());
			e.printStackTrace();
		} finally {
			sc.close();
		}

	}
//try catch자원해제 방법을 finally 안쓰고 java 7버전부터는 다른 구문형식가능
	// ㄴ 관련된 인터페이스가 무엇인지도 찾아보기
}
```
```java
package koreait.day15;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;

//작성자 : 이민호
public class C67_ResourceClose {

	public static void main(String[] args) {

		String filename = "D:\\study\\자바테스트2.txt";

		File file = new File(filename);

		try (PrintWriter pw = new PrintWriter(file);) {
			// ㄴ 괄호 안에 선언함으로서 finally를 안써도 되게 함.
			pw.println("모모 90 89 82");
			pw.println("다현 89 90 82");
			pw.println("나연 82 89 90");
			System.out.println("파일 출력이 완료되었습니다");// System.out : 표준 출력

		} catch (FileNotFoundException e) {
			System.out.println("사용자 오류발생 : " + e.getMessage());
			e.printStackTrace();
		}

		try (Scanner sc = new Scanner(file);) {

			while (sc.hasNext()) {
				System.out.println(sc.nextLine());
			}

			System.out.println("파일 읽기가 완료되었습니다");// System.out : 표준 출력

		} catch (FileNotFoundException e) {
			// 입력기능에는 파일이 없으면 Exception이 발생
			System.out.println("사용자 오류발생 : " + e.getMessage());
			e.printStackTrace();
		}

	}
//try catch자원해제 방법을 finally 안쓰고 java 7버전부터는 다른 구문형식가능
	// try with resource라고 함.
	// ㄴ 관련된 인터페이스가 무엇인지도 찾아보기
	// 선언된 자원이 java.lang.AutoCloseable 인터페이스가 구현되어 있어야 함.
}
```

